### ISSUE TITLE
distribution (--min-coverage and .tsv)

### ISSUE THREAD

**Issue by ferrojm** [INRA-LPGP/RadSex#15]
Hi, 

First, thanks for such amazing and easy to handle protocol. 

I have found two issues: 
The first one, just a minor comment, is that in some places I have seen that is stated that the parameter for coverage in the distrib should be --min-coverage intead of --min-cov, and the former brings an error.

The second issue, likely related to my inexperience, is that after getting the output distribution.tsv. In that table, all data in the third column are 0 and in the fifth column are signif = TRUE, although the p-value varied from 0.003 to 1. I worked just with 13 samples obtained from 3RADseq.

Thanks in advance

**Comment by RomainFeron** [comment]
Hi,
Thanks a lot for using radsex!
I am in the process of updating radsex and the documentation is a bit behind. Thanks for reporting this mistake, I will update it ASAP.

For your second issue, from experience, it's possible that the names of your sample files and individual names in the popmap do not match. Could you post the list of input file names as well as the popmap?

**Comment by ferrojm** [comment]
Thanks for the answer, 

As you say, it was a name issue. I fixed the names and run it again with more samples (n=35), and the output changed.
Unfortunately, for me, all data now turned into FALSE, being possible that these sequences are not informative or should increase my sample.
I attach the output distribution table just in case.

Again, thanks a lot.







[distributionALL.pdf](https://github.com/RomainFeron/RadSex/files/4128291/distributionALL.pdf)

**Comment by RomainFeron** [comment]
I'm glad this problem is solved, I need to add a warning when names don't match.

The distribution results you get are surprising. I generated a tile plot with [radsex-vis](https://github.com/RomainFeron/RADSex-vis):

![distrib](https://user-images.githubusercontent.com/14352967/73368080-b1a0bc80-42b0-11ea-99c8-1925633c89ed.png)

There are no markers found in more than 8 males and/or 4 females, which could mean:
- There are still some mismatches between names of files and names of individuals in the popmap
- Individuals come from different species
- Different individuals were processed with different restriction enzymes
- The individuals you are comparing are extremely genetically diverse, but even in this case you should still have markers shared by all or almost all individuals...

I think the lack of significance comes from the bias in sex for your samples. Significance is computed with a chi-square test on number of males and number of females with Bonferroni correction, which depends on the total number of markers.

Let me know if you found the issue; you can also post the list of input file names and the popmap so I can check if there is anything wrong

**Comment by ferrojm** [comment]
Again, you are right.
Yes, it was an exploration I tried to made with 2 species. That could explain the lack of markers you detected. I tried within a single species but the sample was a small sample.
Here I paste the inputs, although I guess, must focus on one species and decrease the bias in sex.

the paired reads concatenated with "cat"
`Ph06.fastq
Ph07.fastq
Ph08.fastq
Ph09.fastq
Ph10.fastq
Ph11.fastq
Ph12.fastq
Ph13.fastq
Ph14.fastq
Ph15.fastq
Ph16.fastq
Ph17.fastq
Ph18.fastq
Ph19.fastq
Ph20.fastq
Ph21.fastq
Ph22.fastq
Ph23.fastq
Ph24.fastq
Ph25.fastq
Ph26.fastq
Ph27.fastq
Ph28.fastq
Ph29.fastq
Ph30.fastq
Ph31.fastq
Ph32.fastq
Ph33.fastq
Ph35.fastq
Ph36.fastq
Ph37.fastq
Ph38.fastq
Ph39.fastq
Ph40.fastq
Ph41.fastq`

and the popmap
Ph06	M
Ph07	M
Ph08	F
Ph09	F
Ph10	F
Ph11	M
Ph12	M
Ph13	M
Ph14	F
Ph15	M
Ph16	M
Ph17	M
Ph18	M
Ph19	M
Ph20	M
Ph21	M
Ph22	M
Ph23	M
Ph24	M
Ph25	M
Ph26	M
Ph27	F
Ph28	F
Ph29	F
Ph30	M
Ph31	F
Ph32	M
Ph33	M
Ph35	N
Ph36	M
Ph37	M
Ph38	M
Ph39	M
Ph40	M
Ph41	M

I will fetch more samples and try again.
Thanks!

**Comment by RomainFeron** [comment]
Okay, then it makes sense. Your input looks good.
Radsex is particularly sensitive to genetic diversity because a marker corresponds to a single sequence (no snp). It will not work well when missing different species or even very divergent populations.
It's indeed better to have all individuals from the same species with a good balance of males and females (total n=30 is a good baseline; for most species we analyzed with radsex, we had total n closer to 60). You can also play with the minimum depth parameter to filter out low-depth markers and increase significance.
Don't hesitate if you encounter another problem or need more help!
