### ISSUE TITLE
empty distribution output

### ISSUE THREAD

**Issue by Astahlke** [INRA-LPGP/RadSex#16]
Hello!

I'm back to giving this a go (with an improved reference assembly), but getting an empty distribution.tsv from the following command and attached data:

`RadSex/bin/radsex distrib --input-file coverage_table.tsv --output-file distribution.tsv --popmap-file popmap.txt`

`head distribution.tsv`
`Males	Females	Sequences	P	Signif`

Here's the popmap and the first few and last few lines of the coverage_table.tsv output. I also changed the extensions to .txt to allow attachment here.
[popmap_radsex.txt](https://github.com/RomainFeron/RadSex/files/4226751/popmap_radsex.txt)
[coverage_table.txt](https://github.com/RomainFeron/RadSex/files/4226816/coverage_table.txt)

I played around with line endings and column seperators of the popmap file and got this error:
`" for individual "Wi_21" unknown sex "M`

Thanks for any suggestions!

Amanda

**Comment by Astahlke** [comment]
Sorry - here's the popmap that produced the empty output. 
[popmap.txt](https://github.com/RomainFeron/RadSex/files/4226840/popmap.txt)

**Comment by RomainFeron** [comment]
Hey Amanda, really nice to hear from you!
The popmap you uploaded (the second file, popmap.txt) had windows line endings. After converting the line endings to unix ones I was able to run distrib successfully on the sample coverage table that you uploaded. You're not the first person to run into this problem though, so I've pushed a quick fix (bb588f771207f797a59f4a2a95f32704816702e7) that should take care of windows line endings. Could you let me know if the problem is solved after updating radsex?
For info, I'll release a new and improved version of radsex and radsex-vis soon, hopefully in the coming month. If you get nice results with radex, stay tuned ! (with the sample size you have, it should be pretty nice)

**Comment by Astahlke** [comment]
Thanks, Romain! That worked!
![sex_distribution](https://user-images.githubusercontent.com/16710888/74884387-4b97da00-5330-11ea-914e-9613279ed1a3.jpeg)

**Comment by RomainFeron** [comment]
Cool! You got really good results. If you ran it with default value for minimum coverage, I'd try to increase it a bit and see if the results get cleaner. I usually try with 1, 2, 5, and 10 to see how robust the results are (higher values are preferred with high enough sequencing depth)
