### ISSUE TITLE
Found W-linked markers, but no Z-linked

### ISSUE THREAD

**Issue by sheinasim-USDA** [INRA-LPGP/RadSex#17]
Aloha!

Thank you for putting together this very useful program.

I have ddRAD data for several mapping populations of one species of butterflies.

When, I ran my sequences through your analysis pipeline for a broad range of minimum coverages (1-5, 10, 20, 50, 100, 500, 1000), I found many female-biased markers but no male-biased markers.

I predict that it may be because my coverage per locus is very high. Do you think that may be the case? If so, would you recommend down-sampling all of my fastqs to a standard number of average reads per locus?

Thanks!

[vtam_mc20_sex_distribution_plot.pdf](https://github.com/RomainFeron/RadSex/files/4252159/vtam_mc20_sex_distribution_plot.pdf)

**Comment by RomainFeron** [comment]
Hi,
These are really beautiful results! It looks like your species has a pretty large sex locus. In most cases, a minimum coverage of 10 is already pretty stringent.

It's actually expected that you do not find male-biased markers in a ZZ/ZW SD system. This is because RADSex markers are non-polymorphic sequences. In a ZZ/ZW system, assuming differentiation between Z and W alleles, sequences from the W are found only in females, but sequences from the Z are found in both males and females, so there should not be male-specific markers except in specific cases (e.g. a family panel where the mother's Z allele is only passed down to males).

Please let me know if my explanation is not clear or if you have other questions, I'm happy to help! We are currently writing a paper describing RADSex which we hope to release as pre-print soon, it should help to clarify how RADSex works.

**Comment by sheinasim-USDA** [comment]
Aloha Romain,

Thank you for your response. I knew that there would be no male-only markers, but I was hoping that there would be some markers with N coverage in males and N/2 coverage in females. So they would be in the bottom right part of the graph. 

I guess I didn't understand what the program is doing. It is only looking for reads that are found proportionally more in one sex, but if they are found in both (even if there is a significant difference in abundance), they are not considered sex-linked?

Also, can I ask how the mapping is done? Is it using something like BWA?

Thanks!
Sheina

**Comment by RomainFeron** [comment]
No problem, thank you for using radsex!

Yes, it works like you described. For each sequence in the entire dataset, it's counting whether this sequence is present or not in an individual (a marker is considered present if it has a depth higher than the minimum depth set with --min-coverage at the moment). So in the top left you have markers present in females but absent in males, and in the bottom right you have markers present in males but absent in females. And in a normal case, markers with depth N in males and N/2 in females would be in the top right, because they are present in all individuals.

Actually, your question made me realize that depending on the value of --min-coverage, you could expect to find Z markers in the bottom right, if --min-coverage is higher than N/2. In practice, it's a bit tricky, because often individuals have pretty different sequencing depths...

The "loci" module in RADSex was designed identify markers likely to come from the same locus as sex-linked markers using coverage (like you described) and sequence similarity. You could give it a try with the 'radsex loci' command, using the output of 'radsex signif' as input. The results are not really consistent and I've dropped it in my current development version, but I think there's some interest in it though, and I may give it another try after the next release.

The mapping is done using BWA mem algorithm from the BWA library. Only markers uniquely aligned are retained.

**Comment by sheinasim-USDA** [comment]
Thanks so much! I'll try the loci module.

Now that I know, I may just include the markers as potentially W-linked loci. About 100 of them mapped to one chromosome, so it's looking promising.

Cheers,
Sheina

**Comment by RomainFeron** [comment]
That sounds great, really cool results!
If you liked radsex, stay tuned for version 1.0 which I hope to release within two weeks. It will be more polished and nicer to use (I hope)!

Cheers,
Romain

**Comment by sheinasim-USDA** [comment]
Thanks! I will keep an eye out for the next version. This weekend I was able to identify putative Z (or X) scaffolds from my ddRAD data. It complements the RadSex Analysis very nicely! Let me know if it is of interest! 

I will certainly cite RadSex in my next paper (currently in prep).

Cheers,
Sheina

**Comment by RomainFeron** [comment]
That's great!
I'm interested in hearing how you looked for these scaffolds, did use coverage?
I'll be looking forward to your paper!

Cheers,
Romain

**Comment by sheinasim-USDA** [comment]
Hi Romain,

I used vcftools and my .vcf containing biallelic SNPs to calculate heterozygosity for each scaffold and then a t test to identify the scaffolds with a significant difference between male and female heterozygosity.

I uploaded my vcf commands and r scripts here: https://github.com/sheinasim/Find_X_or_Z and a resulting plot is below.

![vtam_z_scaff](https://user-images.githubusercontent.com/7445687/75946357-f637ee80-5e40-11ea-9876-6171299977da.png)

Cheers, and hopefully this is useful to you and others!
Sheina

**Comment by RomainFeron** [comment]
That's really nice, and your results are clean!
One small comment: with this approach, scaffolds specific to females (e.g. W-specific insertion) would not be detected, is that correct?
If you have tried radsex map, did you find the same scaffolds?

Thanks a lot for sharing your results and approach, it's really easy to follow with R markdown :)

**Comment by sheinasim-USDA** [comment]
Yes, these are just identifying potentially Z or X-linked scaffolds based on heterozygosity, and does not identify Y or Ws which is what I used RadSex for. 

Of the 198 significant W-linked loci identified by RadSex, 3 were in scaffolds that I identified as Z-linked using heterozygosity, There was one significant RadSex locus with the opposite sex bias (indicating that it is Z and not W) that was identified as Z-linked using heterozygosity.

If I apply a minimum marker cutoff with the significant RadSex markers to select scaffolds with 2 or more Y or W-linked markers, that eliminates all the overlaps.

**Comment by RomainFeron** [comment]
Interesting, I would expect more overlap, as RADSex should be able to find markers from scaffolds that are "only" differentiated between Z and W (i.e. they're the same scaffold in the assembly but there are W-specific polymorphism). There can be many reasons for this result though.

**Comment by sheinasim-USDA** [comment]
Really? Since my method using heterozygosity identifies scaffolds with depressed heterozygosity in the heterogametic sex (Z and X), I would expect no overlap with RadSex markers that identify W and Y linked markers which only occur in the heterogametic sex.

**Comment by RomainFeron** [comment]
Ah I see, I did not understand it correctly before, but I think I get it now. You're right, RADSex would not identify these markers from the Z chromomsomes :)
