### ISSUE TITLE
Errors with hclust usage

### ISSUE THREAD

**Issue by arthurbensaid** [INRA-LPGP/RadSex#25]
Hello,
I'm currently trying to incorporate RADSex to a snakemake workflow.
I was doing some tests with a subset of the test data used as an example in the documentation (I only downloaded the 5 first individuals of each group to get faster results while testing).
And with each of the steps using Hclust to produce a result, I'm getting the following error: 
Error in hclust(distances, method = clustering_method) : size cannot be NA nor exceed 65536

NB: After checking the results from the first step (radsex process), I saw that I had 6916633 as the max value in my result file.

Do you have any idea of why this happens ? Do you think artificially subsetting the data could lead to problems with the pipeline ?
Could you tell me if you have a better data set for me to test my workflow ?

Thanks for all the help you can give me.

**Comment by RomainFeron** [comment]
Hi,
If I understood correctly, you tried to generate a heatmap of depth for all markers in the results of _process_, is that correct? If that's the case, there are indeed too many markers to cluster. The heatmap/clustering R function was designed to run on a "small" subset of markers (a few thousands at most) to investigate interesting patterns. The results of _process_ are not meant to be analyzed directly in R since there is absolutely no filtering at this stage, not even for sequencing errors.

If I understood wrong and you were using an output file from _subset_ or _signif_, then there is something wrong with the R package and I will have to investigate.

Just in case, if you haven't seen that yet, you can get inspiration from this [workflow](https://github.com/RomainFeron/paper-sexdetermination-radsex) I implemented for the main RADSex paper or this [other workflow](https://github.com/SexGenomicsToolkit/RADSex-workflow) I started putting together as a generic RADSex workflow but didn't get to finish yet.
