### ISSUE TITLE
Handle reads with different size

### ISSUE THREAD

**Issue by BELKHIR** [INRA-LPGP/RadSex#26]
Hi Romain,

In some situations the individual index used for multiplexing sequences can vary in size between individuals.
This will lead, after index removal, to reads with different size depending on the index size.

In this case comparing reads with different sizes will return misleading results !
Is there any advice apart from a pre-treatment with external tails trimming tools ?

Regards,

**Comment by RomainFeron** [comment]
Hi,
You described the problem well and unfortunately there is not really any way to tweak radsex to work with reads of different size. The only solution I can think of is the one you mentioned, i.e. trimming read to a consistent length so that they can be compared. I understand this is not ideal since you lose a little bit of information in some of the reads. What's the size of the reads you're using here? For reference I've used radsex on reads as short as 80bp without issues

**Comment by BELKHIR** [comment]
Hi,

Meanwhile, I have forked radsex and made some changes to deal with our data.
In fact the reads we are dealing with still contains these size variable index sequences.

So I changed the popmap format to have a third column with the sequence of the individual tag.
I created a processTagged option wich needs a popmap file to determine the length of reads to keep (after tag removal and size adjustment via  tail trimming ).  

Now I am faced with a second big problem related to library size variation.  
To avoid a "rarefaction" procedure that have to reduce library size to the same number of reads, I am trying to normalize reads (locus) counts with methods used in rnaseq differential expression analysis (CMP, RPKM ...)

Best regards,

**Comment by RomainFeron** [comment]
Ok, sounds interesting! If you would like, please keep me up with what you find, I'm curious to know. Also don't hesitate if you have questions on the code while doing this.

Cheers,
Romain

**Comment by BELKHIR** [comment]
Hi,
For the moment I just implemented a little solution to normalize reads counts using CPM (counts per million).
This will normally account for sequencing depth differences between samples.

For now I'm  just using this awk script to transform the table of marker depths that is used to compute the distribution of markers between groups and find significantly deviant markers :
 
markerTable=$1
CPMmarkerTable=$2
awk '
{
    if(NR==FNR ){
        if (NR ==2 ) {nbFields = NF}
        if (NR > 2) for (i = 3; i <= NF; i++) a[i]+=$i; #sample total nb reads
        
    }
    else { # reading second file
        if (FNR == 1)
        { 
            print $0
            for (i = 3; i <= nbFields; i++) a[i] = a[i] / 1000000; #per million
            
        }
        if (FNR == 2) { for (i = 1; i <= NF; i++) printf $i "\t"; print ""}
        if (FNR > 2)
        {
            printf "%s\t%s\t",$1,$2
            for (i = 3; i <= nbFields; i++) printf int($i/a[i]) "\t"; #rounded CPM
            print ""
        }
    }

}' $markerTable $markerTable > $CPMmarkerTable

I didn't try it yet on your example data to see if the result is different.

Cheers,

**Comment by BELKHIR** [comment]
An alternative is to made changes in the process procedure to output CPM counts.

Do you think this is a correct way : 

```c++
// Transfer the results from the temp data structure to the full data structure
results_mutex.lock();

//CPM normalization
double nbreads = 0;
for (auto marker : temp_results) {
    nbreads += marker.second;
}

double permillion = nbreads/1000000;

for (auto marker : temp_results) {
    results[marker.first][input_file.individual_name] += round(marker.second / permillion); //rounded CPM counts
}
results_mutex.unlock();
```

Thank's

**Comment by RomainFeron** [comment]
I'm not very familiar with CPM / RNA-Seq analyses but it looks like it should give you the proportion of this read among all reads from this individual * 10^6. Just in case, normalization will happen at the individual level here, not for all the data together. One small optimization would be to lock the mutex before the second loop instead of in the beginning (you're not using "results" until then)

**Comment by BELKHIR** [comment]
Yes CPM normalization is per individual !
Ok for moving the mutex just before changing the results map !

Khalid
